### PR TITLE
Pipeline mesh to label map

### PR DESCRIPTION
**Pull request by Connor-Bowley**
Generic infrastructure for pipelining CLI modules. Not all types (image, pointfile, etc) from CLI modules are implemented. Will implement them on an as needed basis.

### CODE REVIEW

**Comment by sjh26** [comment]
````
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\D\E\AE-2-build\python-install\Lib\imp.py", line 170, in load_source
    module = _exec(spec, sys.modules[name])
  File "<frozen importlib._bootstrap>", line 618, in _exec
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:/SlicerPipelinesBuild/lib/aevaSlicer-4.13/qt-scripted-modules/PipelineModules.py", line 8, in <module>
    from PipelineModulesLib import (
  File "D:\SlicerPipelinesBuild\lib\aevaSlicer-4.13\qt-scripted-modules\PipelineModulesLib\CLIModuleWrapping.py", line 3, in <module>
    from os import EX_CANTCREAT
ImportError: cannot import name 'EX_CANTCREAT'
````

Exit code is linux only: https://docs.python.org/3/library/os.html#os.EX_CANTCREAT

**Comment by sjh26** [comment]
Otherwise, everything is building fine (it seems) on Windows.

**Comment by Connor-Bowley** [comment]
Re: EX_CANCREAT
On occasion my editor likes to be "friendly" and add imports when I accidentally choose the wrong autocomplete. Will update.

**Comment by Connor-Bowley** [comment]
Update pushed.

**Comment by sjh26** [comment]
So, removing that line helps it move along, then I am getting

````
Traceback (most recent call last):
  File "D:/SlicerPipelinesBuild/lib/aevaSlicer-4.13/qt-scripted-modules/PipelineCreator.py", line 347, in _onPopUpAccepted
    buttonHolder.parameters = module.MakeParameters()
  File "D:/SlicerPipelinesBuild/lib/aevaSlicer-4.13/qt-scripted-modules/PipelineCreator.py", line 522, in MakeParameters
    return self._module.GetParameters()
  File "D:\SlicerPipelinesBuild\lib\aevaSlicer-4.13\qt-scripted-modules\PipelineModulesLib\CLIModuleWrapping.py", line 191, in GetParameters
    factory = slicer.qSlicerPipelineCLIModulesBridgeParameterFactory()
AttributeError: module 'slicer' has no attribute 'qSlicerPipelineCLIModulesBridgeParameterFactory'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/SlicerPipelinesBuild/lib/aevaSlicer-4.13/qt-scripted-modules/PipelineCreator.py", line 309, in <lambda>
    popUp.accepted.connect(lambda: self._onPopUpAccepted(popUp))
  File "D:/SlicerPipelinesBuild/lib/aevaSlicer-4.13/qt-scripted-modules/PipelineCreator.py", line 381, in _onPopUpAccepted
    % (name, module.name, str(e)))
UnboundLocalError: local variable 'name' referenced before assignment
````
when trying to add the MeshToLabelmap module.  What paths need to be added from the SlicerPipelines build?

**Comment by sjh26** [comment]
Add headless module for parameter bridge

**Comment by Connor-Bowley** [comment]
Headless module for parameter bridge added

**Review by sjh26 — APPROVED** [review]
Tested w/ mesh to label map, looks good

**Pull request merged**
