### PR TITLE
Pipeline segment editor

### PR DESCRIPTION
**Pull request by Connor-Bowley**
- Pipeline segment editor items
- Pipeline convert model to segmentation
- Add ability to test out pipeline before finalizing it
- Added more VTK filters

### CODE REVIEW

**Comment by sjh26** [comment]
vtk wrappings look good.  I ran into some weird error when removing / adding new modules to a pipeline and running the test again (it looked like there was a model node that was *stuck* in the scene and didn't show up in the data list, but was visible in the 3D view), but I have not been able to reproduce that so 😕 

When running ModelToSegmentation I noted that the reference volume you created is remaining in the scene after the pipeline finished - it should be removed

**Comment by Connor-Bowley** [comment]
> it looked like there was a model node that was stuck in the scene

I previously ran into that before I changed the deletion of intermediate nodes to use the subject hierarchy delete. There was a stray model display node hanging around. I wonder if it would be fixed if I changed the `onRun` of the `XXX.py.template` and `_onRun` of the PipelineCreator to delete using the subject hierarchy.

> When running ModelToSegmentation I noted that the reference volume you created is remaining in the scene after the pipeline finished - it should be removed

Should it though? It is needed for any further segment editor work in the pipeline. And what if the final output of the pipeline is a segmentation? At the same time, if we are iterating through a whole bunch of cases, we don't want a whole bunch of volumes.

Should the volume be set up on some kind of reference counting thing with the segmentations where when all the segmentations are deleted the model should be to? I don't know that there is a clear answer.

**Comment by Connor-Bowley** [comment]
So I found the cause of the leaking display nodes. Calling `vtkMRMLNode::Copy` on a node that has references (in our case, display nodes) causes the references to be invalidated without any kind of cleanup. So I am now manually cleaning up any display and storage nodes that the "copy-into" node had before calling `Copy`.

Side note: because the Subject Hierarchy Logic already does a good job with `CloneSubjectHierarchyItem`, we should consider  making a version that clones into an existing node, rather than just creating a new one.

**Comment by sjh26** [comment]
Leaked display node fix looks good.  Re: reference volume, I think it would be helpful to name it something so that it does not look like leftover intermediate data i.e. "ModelName Segmentation Master Volume"

**Review by sjh26 — APPROVED** [review]

**Comment by Connor-Bowley** [comment]
I will update convert model to segmentation to take a name for the reference volume

**Pull request merged**
